from dataclasses import dataclass

from engine.src.chunker import CodeChunk


@dataclass(frozen=True, slots=True)
class ChunkFilterConfig:
    """
    Chunk quality filtering and selection configuration.

    min_chunk_bytes: int — Minimum UTF-8 byte length for a chunk to be kept.
    max_chunks_per_file: int — Maximum number of chunks kept per file.
    skip_minified: bool — Skip chunks from likely minified/noise-heavy files.
    max_line_length: int — Threshold line length used by minified detection.
    min_avg_line_length: int — Threshold average line length used by minified detection.
    """

    min_chunk_bytes: int = 120
    max_chunks_per_file: int = 400
    skip_minified: bool = True
    max_line_length: int = 1200
    min_avg_line_length: int = 220


@dataclass(frozen=True, slots=True)
class ChunkFilterStats:
    """
    Filtering statistics for index pipeline reporting.

    input_chunks: int — Total chunks before filtering.
    kept_chunks: int — Chunks kept after filtering.
    skipped_small: int — Chunks skipped due to min byte threshold.
    skipped_minified: int — Chunks skipped due to minified/noise heuristics.
    skipped_per_file_cap: int — Chunks dropped by per-file cap.
    files_capped: int — Number of files where cap was applied.
    """

    input_chunks: int
    kept_chunks: int
    skipped_small: int
    skipped_minified: int
    skipped_per_file_cap: int
    files_capped: int


def filter_chunks(chunks: list[CodeChunk], config: ChunkFilterConfig) -> tuple[list[CodeChunk], ChunkFilterStats]:
    """
    Filter and select high-value chunks for faster indexing.

    chunks: list[CodeChunk] — Raw chunks generated by chunker.
    config: ChunkFilterConfig — Filtering and selection settings.
    Returns: tuple[list[CodeChunk], ChunkFilterStats] — Filtered chunks and stats.
    """
    grouped: dict[str, list[CodeChunk]] = {}
    for chunk in chunks:
        grouped.setdefault(chunk.file_path, []).append(chunk)

    kept: list[CodeChunk] = []
    skipped_small = 0
    skipped_minified = 0
    skipped_per_file_cap = 0
    files_capped = 0

    for file_path, file_chunks in grouped.items():
        candidates: list[CodeChunk] = []

        for chunk in file_chunks:
            source = chunk.source or ""
            byte_len = len(source.encode("utf-8", errors="ignore"))
            if byte_len < config.min_chunk_bytes:
                skipped_small += 1
                continue

            if config.skip_minified and _is_minified_like(source, config):
                skipped_minified += 1
                continue

            candidates.append(chunk)

        if len(candidates) > config.max_chunks_per_file:
            files_capped += 1
            scored = sorted(candidates, key=_chunk_quality_score, reverse=True)
            kept.extend(scored[: config.max_chunks_per_file])
            skipped_per_file_cap += len(candidates) - config.max_chunks_per_file
        else:
            kept.extend(candidates)

    stats = ChunkFilterStats(
        input_chunks=len(chunks),
        kept_chunks=len(kept),
        skipped_small=skipped_small,
        skipped_minified=skipped_minified,
        skipped_per_file_cap=skipped_per_file_cap,
        files_capped=files_capped,
    )
    return kept, stats


def _chunk_quality_score(chunk: CodeChunk) -> float:
    """
    Compute a lightweight quality score for chunk selection.

    chunk: CodeChunk — Candidate chunk.
    Returns: float — Higher means better signal for indexing.
    """
    source = chunk.source or ""
    lines = source.splitlines()
    line_count = max(1, len(lines))
    byte_len = len(source.encode("utf-8", errors="ignore"))

    alpha_chars = sum(1 for c in source if c.isalpha())
    non_alnum = sum(1 for c in source if not c.isalnum() and not c.isspace())

    alpha_ratio = alpha_chars / max(1, len(source))
    symbol_ratio = non_alnum / max(1, len(source))

    score = 0.0
    score += min(byte_len / 500.0, 12.0)
    score += min(line_count / 20.0, 6.0)
    score += alpha_ratio * 6.0
    score += (1.0 - min(symbol_ratio, 1.0)) * 2.5

    if chunk.signature:
        score += 1.5
    if chunk.docstring:
        score += 1.0
    if chunk.symbol_kind and chunk.symbol_kind != "file":
        score += 0.8

    return score


def _is_minified_like(source: str, config: ChunkFilterConfig) -> bool:
    """
    Heuristic detection for minified/noise-heavy chunks.

    source: str — Chunk source text.
    config: ChunkFilterConfig — Threshold settings.
    Returns: bool — True when chunk is likely minified/noisy.
    """
    if not source:
        return False

    lines = source.splitlines()
    if not lines:
        return False

    max_line = max(len(line) for line in lines)
    avg_line = sum(len(line) for line in lines) / len(lines)

    if max_line >= config.max_line_length:
        return True

    if len(lines) <= 6 and avg_line >= config.min_avg_line_length:
        return True

    whitespace_ratio = sum(1 for c in source if c.isspace()) / max(1, len(source))
    if len(lines) <= 3 and whitespace_ratio < 0.04 and avg_line > 120:
        return True

    return False
